

import { Project, Skill, Certification } from './types';

export const PROJECTS: Project[] = [
  {
    title: 'Customer Churn Prediction Chatbot',
    description: 'Built a full-stack AI chatbot using React and Flask to predict customer churn for OTT and banking services, complete with interactive dashboards to visualize churn probabilities and key drivers.',
    tags: ['Python', 'Flask', 'React', 'Random Forest', 'Data Visualization'],
    imageUrl: 'https://raw.githubusercontent.com/KarthikUppalapati57/MyPortifolio/331a2a5915cc3979523c22398d9a3b98a23fc211/Google_AI_Studio_2025-07-16T00_40_06.599Z.png',
    sourceUrl: 'https://github.com/karthikuppalapati57/customer-churn',
  },
  {
    title: 'Hospital Readmission Prediction',
    description: 'Developed and implemented machine learning techniques with Python, Scikit-learn, and Pandas to analyze inpatient data, enabling the early identification of diabetic patients at higher risk of readmission.',
    tags: ['Machine Learning', 'Python', 'Scikit-learn', 'Pandas', 'Healthcare'],
    imageUrl: 'https://raw.githubusercontent.com/KarthikUppalapati57/MyPortifolio/b5e24e911c32a037285892ee5ae1c6900c5d2884/Hospital%20Readmission.484Z.png',
    sourceUrl: 'https://github.com/karthikuppalapati57/Hospital-Readmission-using-ML',
  },
  {
    title: 'Comparative Analysis of Quantum Machines',
    description: 'Conducted a detailed comparative assessment of classical and quantum cryptography methodologies, identifying superior algorithms to strengthen the security framework for communication protocols.',
    tags: ['Quantum Cryptography', 'Security', 'Research'],
    imageUrl: 'https://raw.githubusercontent.com/KarthikUppalapati57/MyPortifolio/b5e24e911c32a037285892ee5ae1c6900c5d2884/quantum%20vs%20Classic.410Z.png',
    sourceUrl: 'https://github.com/karthikuppalapati57',
  },
    {
    title: 'CP-ABE On Cloud Security',
    description: 'Developed and implemented an advanced cryptographic model leveraging Dynamic Key Generation and QH-CPABE, enhancing data security and access control for cloud storage solutions on AWS.',
    tags: ['Cloud Computing', 'Cryptography', 'AWS', 'Security'],
    imageUrl: 'https://raw.githubusercontent.com/KarthikUppalapati57/MyPortifolio/b5e24e911c32a037285892ee5ae1c6900c5d2884/Cp-abe.549Z.png',
    sourceUrl: 'https://github.com/karthikuppalapati57/CP-ABE',
  },
];

export const MINI_PROJECTS: Project[] = [
  {
    title: 'Multimodal IMDB Analysis with Keras',
    description: 'An advanced analysis of the IMDB dataset combining both text reviews and associated metadata using Keras. This project explores multimodal model architectures to improve sentiment prediction accuracy.',
    tags: ['Keras', 'TensorFlow', 'Python', 'NLP', 'Multimodal AI'],
    imageUrl: 'https://raw.githubusercontent.com/KarthikUppalapati57/MyPortifolio/a86fdf2822c3e6ba14773bea9aeebf78d3ab0390/Multimodal%20IMDB%20Analysis%20with%20Keras.091Z.png',
    sourceUrl: 'https://github.com/karthikuppalapati57',
  }
];

export const CERTIFICATIONS: Certification[] = [
  {
    name: 'Prompt Design in Vertex AI',
    issuer: 'Google Cloud Skills Boost',
    description: 'Learned advanced techniques for designing and engineering effective prompts for large language models within the Vertex AI ecosystem.',
    url: 'https://www.cloudskillsboost.google/public_profiles/cf97ee7a-dc09-44a0-aea8-af1961e3d424/badges/16377587',
    category: 'Generative AI',
  },
  {
    name: 'Build Real World AI Applications with Gemini and Imagen',
    issuer: 'Google Cloud Skills Boost',
    description: 'Gained practical experience building real-world applications using the Gemini and Imagen APIs for multimodal AI solutions.',
    url: 'https://www.cloudskillsboost.google/public_profiles/cf97ee7a-dc09-44a0-aea8-af1961e3d424/badges/16449270',
    category: 'Generative AI',
  },
  {
    name: 'Develop Gen AI Apps with Gemini and Streamlit',
    issuer: 'Google Cloud Skills Boost',
    description: 'Acquired skills to develop and deploy generative AI applications quickly using the Gemini API and the Streamlit framework.',
    url: 'https://www.cloudskillsboost.google/public_profiles/cf97ee7a-dc09-44a0-aea8-af1961e3d424',
    category: 'Generative AI',
  },
  {
    name: 'Inspect Rich Documents with Gemini Multimodality and Multimodal RAG',
    issuer: 'Google Cloud Skills Boost',
    description: 'Explored advanced multimodal capabilities of Gemini and RAG to inspect and analyze complex, rich-media documents.',
    url: 'https://www.cloudskillsboost.google/public_profiles/cf97ee7a-dc09-44a0-aea8-af1961e3d424/badges/16617601',
    category: 'Generative AI',
  },
  {
    name: 'Explore Generative AI with the Gemini API in Vertex AI',
    issuer: 'Google Cloud Skills Boost',
    description: 'Gained hands-on experience using the Gemini API through Vertex AI for a variety of generative AI tasks and explorations.',
    url: 'https://www.cloudskillsboost.google/public_profiles/cf97ee7a-dc09-44a0-aea8-af1961e3d424/badges/16832874',
    category: 'Generative AI',
  },
  {
    name: 'Forward Program',
    issuer: 'McKinsey & Company',
    description: 'Completed a comprehensive program focused on practical business skills, leadership capabilities, and digital transformation.',
    url: 'https://www.credly.com/badges/9f7423f1-757d-4d0a-ab77-1b86ac633094/public_url',
    category: 'McKinsey',
  },
   {
    name: 'Create User Stories in Jira',
    issuer: 'Atlassian',
    description: 'Learned to create and manage user stories effectively within the Jira platform for agile project management.',
    url: 'https://coursera.org/share/65dc816418d2fb1c0abc253a43da37ea',
    category: 'Software Development & Management',
  },
  {
    name: 'Build a Product Roadmap with Aha!',
    issuer: 'Aha!',
    description: 'Gained skills in building and managing a product roadmap using the Aha! software.',
    url: 'https://coursera.org/share/0b762add66f70d9cd0db5c210bdb0915',
    category: 'Software Development & Management',
  },
  {
    name: 'Create User Stories in Miro',
    issuer: 'Miro',
    description: 'Mastered the technique of creating and collaborating on user stories using the Miro visual workspace.',
    url: 'https://coursera.org/share/1f28d3db8c9fba00116d921e8881540e',
    category: 'Software Development & Management',
  },
  {
    name: 'Introduction to Software Testing',
    issuer: 'University of Minnesota',
    description: 'Covered the fundamentals of software testing, including different testing levels and techniques.',
    url: 'https://coursera.org/share/e3563403b7d113657af22dac98a19a30',
    category: 'Software Development & Management',
  },
  {
    name: 'Design Thinking for Innovation',
    issuer: 'University of Virginia',
    description: 'Mastered the innovation process from identifying opportunities to generating and testing new ideas.',
    url: 'https://coursera.org/share/41ca7face007aa5795aeb13eec020484',
    category: 'Coursera',
  },
  {
    name: 'Introduction to Artificial Intelligence (AI)',
    issuer: 'IBM',
    description: 'Explored the foundational concepts of AI, its applications, and its societal implications.',
    url: 'https://coursera.org/share/dedc2823ae028a891f31c45bff5e9d90',
    category: 'Coursera',
  },
  {
    name: 'Building Smart Business Assistants with IBM Watson',
    issuer: 'IBM',
    description: 'Learned to build and deploy intelligent chatbots using IBM Watson Assistant.',
    url: 'https://coursera.org/share/53dca0597e5b6279f5eb267cfea3e26c',
    category: 'Coursera',
  },
  {
    name: 'Technical Support Fundamentals',
    issuer: 'Google',
    description: 'Acquired foundational skills in IT support, including troubleshooting and customer service.',
    url: 'https://coursera.org/share/c348f16d393b5d9893209a31ba738f26',
    category: 'Coursera',
  },
  {
    name: 'Data Structures',
    issuer: 'University of California San Diego',
    description: 'Gained proficiency in designing and implementing common data structures for problem-solving.',
    url: 'https://coursera.org/share/efb7c4a4a82ccb806eb3ad6a8c6131f5',
    category: 'Coursera',
  },
  {
    name: 'Implementing Hangman Game Using Basics of Python 3',
    issuer: 'University of Michigan',
    description: 'Applied fundamental Python 3 concepts to build a classic Hangman game from scratch.',
    url: 'https://coursera.org/share/f136e05a7836d5dc45635b55c4f93c30',
    category: 'Coursera',
  },
  {
    name: 'Global Environmental Management',
    issuer: 'Technical University of Denmark (DTU)',
    description: 'Explored principles of environmental management and sustainability on a global scale.',
    url: 'https://coursera.org/share/a3f9906d19ed51fb592578887829e544',
    category: 'Coursera',
  },
  {
    name: 'Logic for Economists',
    issuer: 'University of Amsterdam',
    description: 'Developed skills in logical reasoning and its application within the field of economics.',
    url: 'https://coursera.org/share/83204aa024fb0e3751c02263985cad36',
    category: 'Coursera',
  },
  {
    name: 'The Bits and Bytes of Computer Networking',
    issuer: 'Google',
    description: 'Learned the fundamentals of modern networking technologies and protocols.',
    url: 'https://coursera.org/share/94f74b8b494329afae542ae5a5c907e1',
    category: 'Coursera',
  },
  {
    name: 'Operating Systems and You: Becoming a Power User',
    issuer: 'Google',
    description: 'Gained skills to manage and configure common operating systems like Windows and Linux.',
    url: 'https://coursera.org/share/7444d109b6a114016e9ec6e2775dea96',
    category: 'Coursera',
  },
  {
    name: 'Biology Everywhere Foundations',
    issuer: 'University of Colorado Boulder',
    description: 'Explored foundational concepts in biology and their relevance in everyday life.',
    url: 'https://coursera.org/share/d7f01473c6bcaac1aef72ccefecc33a3',
    category: 'Coursera',
  },
  {
    name: 'The Little Stuff: Energy, Cells, and Genetics',
    issuer: 'University of Colorado Boulder',
    description: 'Delved into the core biological topics of cellular energy, structure, and genetics.',
    url: 'https://coursera.org/share/f85a37c9ecc722a404f9a71a98c9ff04',
    category: 'Coursera',
  },
  {
    name: 'Applying Data Structures to Manipulate Cleansed UN Data',
    issuer: 'University of Michigan',
    description: 'Applied data structures and Python to perform complex manipulations on real-world datasets.',
    url: 'https://coursera.org/share/acb95943af9a6b4001338127fce6ddb2',
    category: 'Coursera',
  },
  {
    name: 'Blockchain Scalability and its Foundations',
    issuer: 'University at Buffalo',
    description: 'Studied blockchain scalability challenges and their foundations in distributed systems.',
    url: 'https://coursera.org/share/429e4a44c72063bfe331a3d306ba4d50',
    category: 'Coursera',
  },
  {
    name: 'Mathematical Foundations for Cryptography',
    issuer: 'University of Colorado System',
    description: 'Learned the essential mathematical principles that underpin modern cryptographic systems.',
    url: 'https://coursera.org/share/7d4e34af97169e3d5d794206c1929af3',
    category: 'Coursera',
  },
  {
    name: 'Database Management Essentials',
    issuer: 'University of Colorado System',
    description: 'Covered the essentials of database management, including relational databases and SQL.',
    url: 'https://coursera.org/share/14b81786469763a1d63eae99b3e876d6',
    category: 'Coursera',
  },
  {
    name: 'Good with Words: Writing and Editing',
    issuer: 'University of Michigan',
    description: 'Enhanced skills in writing and editing, from crafting compelling sentences to structuring complex documents.',
    url: 'https://coursera.org/share/941c13d26420dfa01f3533d083eb4485',
    category: 'Coursera',
  },
  {
    name: 'Cloud Computing Basics (Cloud 101)',
    issuer: 'LearnQuest',
    description: 'Gained a foundational understanding of cloud computing concepts, models, and services.',
    url: 'https://coursera.org/share/fb1782509ab9d78b4228edae13fcfb56',
    category: 'Coursera',
  },
  {
    name: 'Introduction to Web Development',
    issuer: 'University of California, Davis',
    description: 'Learned the basics of web development, including HTML, CSS, and JavaScript fundamentals.',
    url: 'https://coursera.org/share/e7794afe3e82bce731c9ee41225a51ef',
    category: 'Coursera',
  },
  {
    name: 'TCP/IP and Advanced Topics',
    issuer: 'University of Colorado System',
    description: 'Explored the TCP/IP protocol suite and other advanced networking topics in depth.',
    url: 'https://coursera.org/share/da202dd3d8967ac2083d3f7fea04444a',
    category: 'Coursera',
  },
  {
    name: 'International Leadership and Organizational Behavior',
    issuer: 'Bocconi University',
    description: 'Studied leadership principles and organizational behavior in a global context.',
    url: 'https://coursera.org/share/2eb2e1300d2a22257908ad3687798fd6',
    category: 'Coursera',
  },
  {
    name: 'Think Again I: How to Understand Arguments',
    issuer: 'Duke University',
    description: 'Developed critical thinking skills for analyzing and evaluating arguments.',
    url: 'https://coursera.org/share/cf3fdad',
    category: 'Coursera',
  },
];

export const SKILLS: Skill[] = [
  // AI & Data Science
  { name: 'Python', category: 'AI & Data Science' },
  { name: 'Machine Learning', category: 'AI & Data Science' },
  { name: 'Generative AI', category: 'AI & Data Science' },
  { name: 'Vertex AI', category: 'AI & Data Science' },
  { name: 'Natural Language Processing (NLP)', category: 'AI & Data Science' },
  { name: 'Prompt Engineering', category: 'AI & Data Science' },
  { name: 'Scikit-learn', category: 'AI & Data Science' },
  { name: 'Pandas', category: 'AI & Data Science' },
  
  // Web & Backend
  { name: 'React', category: 'Web & Backend' },
  { name: 'Flask', category: 'Web & Backend' },
  { name: 'Web Development', category: 'Web & Backend' },
  { name: 'SQL', category: 'Web & Backend' },
  { name: 'DBMS', category: 'Web & Backend' },
  { name: 'AWS', category: 'Web & Backend' },
  { name: 'Docker', category: 'Web & Backend' },
  { name: 'Apache', category: 'Web & Backend' },
  { name: 'C', category: 'Web & Backend' },

  // Tools & Platforms
  { name: 'Windows', category: 'Tools & Platforms' },
  { name: 'MacOS', category: 'Tools & Platforms' },
  { name: 'Microsoft Office', category: 'Tools & Platforms' },
  { name: 'WordPress', category: 'Tools & Platforms' },
  { name: 'Wappalyzer', category: 'Tools & Platforms' },
  { name: 'My SQL', category: 'Tools & Platforms' },
];